config/routes.rb
Explore::Application.routes.draw do
  resources :grids

  get "home/index"

  root :to => 'home#index' 
 

end

app/models/grid.rb
class Grid < ActiveRecord::Base
  attr_accessible :grid_x, :grid_y
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/grids_controller.rb
class GridsController < ApplicationController
  # GET /grids
  # GET /grids.json
  def index
    @grids = Grid.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grids }
    end
  end

  # GET /grids/1
  # GET /grids/1.json
  def show
    @grid = Grid.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @grid }
    end
  end

  # GET /grids/new
  # GET /grids/new.json
  def new
    @grid = Grid.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @grid }
    end
  end

  # GET /grids/1/edit
  def edit
    @grid = Grid.find(params[:id])
  end

  # POST /grids
  # POST /grids.json
  def create
    @grid = Grid.new(params[:grid])

    respond_to do |format|
      if @grid.save
        format.html { redirect_to @grid, notice: 'Grid was successfully created.' }
        format.json { render json: @grid, status: :created, location: @grid }
      else
        format.html { render action: "new" }
        format.json { render json: @grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /grids/1
  # PUT /grids/1.json
  def update
    @grid = Grid.find(params[:id])

    respond_to do |format|
      if @grid.update_attributes(params[:grid])
        format.html { redirect_to @grid, notice: 'Grid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grids/1
  # DELETE /grids/1.json
  def destroy
    @grid = Grid.find(params[:id])
    @grid.destroy

    respond_to do |format|
      format.html { redirect_to grids_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grids_helper.rb
module GridsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/grids/_form.html.erb
<%= form_for @grid, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :grid_x, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :grid_x, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :grid_y, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :grid_y, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                grids_path, :class => 'btn' %>
  </div>
<% end %>

app/views/grids/edit.html.erb
<%- model_class = Grid -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/grids/index.html.erb
<%- model_class = Grid -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:grid_x) %></th>
      <th><%= model_class.human_attribute_name(:grid_y) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @grids.each do |grid| %>
      <tr>
        <td><%= link_to grid.id, grid_path(grid) %></td>
        <td><%= grid.grid_x %></td>
        <td><%= grid.grid_y %></td>
        <td><%=l grid.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_grid_path(grid), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      grid_path(grid),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_grid_path,
            :class => 'btn btn-primary' %>

app/views/grids/new.html.erb
<%- model_class = Grid -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/grids/show.html.erb
<%- model_class = Grid -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:grid_x) %>:</strong></dt>
  <dd><%= @grid.grid_x %></dd>
  <dt><strong><%= model_class.human_attribute_name(:grid_y) %>:</strong></dt>
  <dd><%= @grid.grid_y %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              grids_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_grid_path(@grid), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              grid_path(@grid),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NASA - Mars Mission 2012</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="background-image:url('/images/sky.jpg');">
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/home/index">NASA - Mars Mission 2012</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Home", "/home/index" %></li>
            <li><%= link_to "Report a bug" %></li>
            <li><%= link_to "Launch a new rover", "/rovers/new" %></li>
            <li><%= link_to "Get Help", "/grids/(self.id)" %></li>
            <li><%= link_to "Version Information", "/version/index" %></li>
        </div>
      </div>
    </div>
  </div>

<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

  <div class="container">
    <div class="row">
      <div class="span7"><%= yield %></div>
      <div class="span5">
        <h2>Statement by the President on Curiosity Landing on Mars</h2>
        <h5>THE WHITE HOUSE</h5>
	<h5>Office of the Press Secretary</h5>
        <p>August 6, 2012</p>
	<p>Tonight, on the planet Mars, the United States of America made history.</p>
	<p>The successful landing of Curiosity – the most sophisticated roving laboratory ever to land on another planet – marks an unprecedented feat of technology that will stand as a point of national pride far into the future. It proves that even the longest of odds are no match for our unique blend of ingenuity and determination.</p>
	<p>Tonight’s success, delivered by NASA, parallels our major steps forward towards a vision for a new partnership with American companies to send American astronauts into space on American spacecraft. That partnership will save taxpayer dollars while allowing NASA to do what it has always done best – push the very boundaries of human knowledge. And tonight’s success reminds us that our preeminence – not just in space, but here on Earth – depends on continuing to invest wisely in the innovation, technology, and basic research that has always made our economy the envy of the world.</p>
	<p>I congratulate and thank all the men and women of NASA who made this remarkable accomplishment a reality – and I eagerly await what Curiosity has yet to discover.</p>
      </div>
    </div>
  </div>
</body>
</html>